coverage:
  status:
    project:
      default: off
      test:
        target: 0%
        threshold: 1%
        flags: test
      integration:
        target: 0%
        threshold: 1%
        flags: integration
